---
# tasks file for verygood.hardening

- name: define ssh service name
  set_fact:
    ssh_service_name: "sshd"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Amazon'

- name: auto logout for shell
  template: src=shell-timeout.sh.j2 dest=/etc/profile.d/shell-timeout.sh mode=0644 owner=root group=root
  when: vg_hardening_shell_timeout_seconds > 0
  tags: hardening

- name: remove root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin.*" line="PermitRootLogin no"
  tags: hardening
  notify: restart sshd

- name: remove requiretty from sudoers
  lineinfile: dest=/etc/sudoers regexp="^Defaults(\s+\t+)requiretty" state=absent
  tags: hardening

- name: tight up ssh ciphers
  lineinfile: dest=/etc/ssh/{{item}}
    state=present
    regexp='^Ciphers'
    line='Ciphers aes256-ctr,aes192-ctr,aes128-ctr'
  tags: hardening
  notify: restart sshd
  with_items:
    - sshd_config
    - ssh_config

- name: tight up macs ciphers
  lineinfile: dest=/etc/ssh/{{item}}
    state=present
    regexp='^MACs'
    line='MACs hmac-sha2-512,hmac-sha2-256'
  tags: hardening
  notify: restart sshd
  with_items:
    - sshd_config
    - ssh_config

- name: tight up KexAlgorithms
  lineinfile: dest=/etc/ssh/{{item}}
    state=present
    regexp='^KexAlgorithms'
    line='KexAlgorithms curve25519-sha256,ecdh-sha2-nistp384,ecdh-sha2-nistp256'
  tags: hardening
  notify: restart sshd
  with_items:
    - sshd_config
    - ssh_config

- name: define CASignatureAlgorithms
  lineinfile: dest=/etc/ssh/{{item}}
    state=present
    regexp='^CASignatureAlgorithms'
    line='CASignatureAlgorithms ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa'
  tags: hardening
  notify: restart sshd
  with_items:
    - sshd_config

- name: removing world write/execute permissions from python dist packages
  file: dest=/usr/local/lib/python2.7/dist-packages recurse=yes state=directory mode="o-wx"
