---
# tasks file for verygood.hardening

- name: auto logout for shell
  template: src=shell-timeout.sh.j2 dest=/etc/profile.d/shell-timeout.sh mode=0644 owner=root group=root
  when: vg_hardening_shell_timeout_seconds > 0
  tags: hardening

- name: remove root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin.*" line="PermitRootLogin no"
  tags: hardening
  notify: restart sshd

- name: remove requiretty from sudoers
  lineinfile: dest=/etc/sudoers regexp="^Defaults(\s+\t+)requiretty" state=absent
  tags: hardening

- name: tight up ssh ciphers
  lineinfile:
    dest=/etc/ssh/{{item}}
    state=present
    regexp='^Ciphers'
    line='Ciphers aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc'
  tags: hardening
  notify: restart sshd
  with_items:
    - sshd_config
    - ssh_config

- name: tight up macs ciphers
  lineinfile:
    dest=/etc/ssh/{{item}}
    state=present
    regexp='^MACs'
    line='MACs hmac-sha1'
  tags: hardening
  notify: restart sshd
  with_items:
    - sshd_config
    - ssh_config

- name: removing world write/execute permissions from python dist packages
  file: dest=/usr/local/lib/python2.7/dist-packages recurse=yes state=directory mode="o-wx"

- name: define ssh service name
  set_fact:
    ssh_service_name: 'sshd'
  when: ansible_distribution == 'CentOS'
